export const weatherIcons: { [key: string]: string } = {
  "clear-day": "img/clear-day.png",
  "clear-night": "img/clear-night.png",
  cloudy: "img/cloudy.png",
  fog: "img/fog.png",
  hail: "img/hail.png",
  "partly-cloudy-day": "img/partly-cloudy-day.png",
  "partly-cloudy-night": "img/partly-cloudy-night.png",
  "rain-snow-showers-day": "img/rain-snow-showers-day.png",
  "rain-snow-showers-night": "img/rain-snow-showers-night.png",
  "rain-snow": "img/rain-snow.png",
  rain: "img/rain.png",
  "showers-day": "img/showers-day.png",
  "showers-night": "img/showers-night.png",
  sleet: "img/sleet.png",
  "snow-showers-day": "img/snow-showers-day.png",
  "snow-showers-night": "img/snow-showers-night.png",
  snow: "img/snow.png",
  "thunder-rain": "img/thunder-rain.png",
  "thunder-showers-day": "img/thunder-showers-day.png",
  "thunder-showers-night": "img/thunder-showers-night.png",
  thunder: "img/thunder.png",
  wind: "img/wind.png",
};
